### ISSUE TITLE
List in marketplace

### ISSUE THREAD

**Issue by erikpetzold** [vaulttec/veloedit#6]
Hi,

first of all, thank you for providing an updated velocity plugin (without having to install plugin 2.0-style support and so on).

It would be very nice if you would list this plugin in the eclipse marketplace. It's very easy, you just have to fill a little form and provide a link to the already existing update site.
For users this makes it easier to find, install and remember the plugin.

Thank you

**Comment by erikpetzold** [comment]
I still can not find it in marketplace via search... tried with "veloedit", "velocity", "vaulttec"

The install button for drag and drop is nice, but I would like to star it in marketplace, to easy find it again.

**Comment by tjuerge** [comment]
Hang on a sec - the Marketplace entry has to be moderated first:
![screenshot-eclipsemarketplace](https://cloud.githubusercontent.com/assets/2626998/16986378/8186d4e8-4e86-11e6-84ab-b1a5ada3e77c.png)
