### ISSUE TITLE
Installation-details screenshot shows old SourceForce-hosted URL

### ISSUE THREAD

**Issue by ChristopherSchultz** [vaulttec/veloedit#8]
The screenshot linked from the GitHub-hosted page still shows the old sf-hosted VeloEdit Eclipse-updates URL.

Also it would be nice if the installation information would state (if true, I'm not sure since I already did it and can't easily go back) that the "Eclipse 2.0 Style Plugin Support" plug-in is required for certain later versions of Eclipse (e.g. Mars, Neon, etc.).

**Comment by tjuerge** [comment]
Updated installation details can be found in [README.md](../blob/develop/README.md#installation).

The "Eclipse 2.0 Style Plugin Support" plug-in is not required any more. All uses of the old Eclipse 2.0 API has been removed in #2.
