### ISSUE TITLE
Syntax Highlighting on Mars/Neon

### ISSUE THREAD

**Issue by renebrain** [vaulttec/veloedit#9]
Hey,

does this Tool even work on Mars or Neon? I installed the repository on my eclipse and also installed 'Eclipse 2.0 Style Plugin Support' but it still shows me the entire html code in black color. Only HashValues are shown in pink color.

Is this a bug or is some more setup necessary to get this plugin going?

![syntax](https://cloud.githubusercontent.com/assets/9963399/18624522/a84ac91c-7e48-11e6-9e49-f206cba97fbe.jpg)

**Comment by tjuerge** [comment]
Starting with version 1.0.6 this plugin is Eclipse 4 compliant and doesn't need the "Eclipse 2.0 Style Plugin Support" anymore.

**Comment by tjuerge** [comment]
This plugin is only aware of Velocity template code (VTL). So syntax highlighting is only available for VTL. All the other stuff (HTML, XML, ...) is only plain text.

So, it's not a bug, it's a feature ;-)
